// Mock data for user information

export const USERS = [
  {
    _id: "0",
    firstname: "John",
    lastname: "Doe",
    image: "/assets/images/johndoe.jpg",
    email: "johndoe1989@gmail.com",
    FbOAuth: "",
    GoogleOAuth: "",
    AppleOAuth: "",
    admin: false,
    favEBooks: [],
    cart: [],
  },
  {
    _id: "1",
    firstname: "Jane",
    lastname: "Doe",
    image: "/assets/images/janedoe.jpg",
    email: "janedoe1984@gmail.com",
    FbOAuth: "",
    GoogleOAuth: "",
    AppleOAuth: "",
    admin: false,
    favEBooks: [],
    cart: [],
  },
  {
    _id: "2",
    firstname: "Admin",
    lastname: "Doe",
    image: "/assets/images/admin.jpg",
    email: "admin@ebook.com",
    FbOAuth: "",
    GoogleOAuth: "",
    AppleOAuth: "",
    admin: true,
    favEBooks: [],
    cart: [],
  },
];
